spring.application.name=tickettriage

spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_triage_db
spring.datasource.username=system
spring.datasource.password=system
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

server.port=8080